site_name: WebFramework
site_url: https://web-framework.com
theme:
  name: material
  features:
    - navigation.expand
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Core Concepts:
    - entities-and-repositories.md
    - configuration.md
    - dependency-injection.md
    - new-entity.md
  - Request Handling:
    - routing.md
    - middlewares.md
    - emitting-responses.md
    - input-validation.md
    - templating.md
  - Database:
    - database.md
    - database-migrations.md
    - caching.md
  - Additional Features:
    - instrumentation.md
    - translations.md
    - sanity-checks.md
    - tasks.md

